import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Image from "next/image";

const Home: NextPage = () => {
    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['mint-page-main']}>
          <div className={styles['nft-table-container']}>
              <Image src={'/images/nft-table.svg'} alt={'nft-table'} layout='fill' objectFit='contain'/>

              <div className={`${styles['content-container']}`}>
                  <h1 className={`${styles['content-title']} text-white text-center`}>How many NFTs do you want to mint?</h1>
              </div>
          </div>
      </main>

    </div>
  )
}

export default Home
