import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles['mint-page-main']}>
          <div>
              {/*<Image src={'/images/clouds.svg'} alt={'clouds'} layout={'fill'}/>*/}
          </div>
      </main>

    </div>
  )
}

export default Home
